package dao; import java.sql.*; import model.Room; import util.db;
public class RoomDAO {
    private void print(ResultSet rs)throws Exception{System.out.println(rs.getInt("id")+" | Room:"+rs.getString("room_number")+" | "+rs.getString("type")+" | Guest:"+rs.getString("guest_name")+" | Rs."+rs.getDouble("price_per_night")+"/night | "+rs.getString("check_in")+" to "+rs.getString("check_out")+" | "+rs.getString("status"));}
    public boolean add(Room r){try{PreparedStatement ps=db.getConnection().prepareStatement("INSERT INTO rooms(room_number,type,guest_name,price_per_night,check_in,check_out,status)VALUES(?,?,?,?,?,?,?)");ps.setString(1,r.getRoomNumber());ps.setString(2,r.getType());ps.setString(3,r.getGuestName());ps.setDouble(4,r.getPricePerNight());ps.setString(5,r.getCheckIn());ps.setString(6,r.getCheckOut());ps.setString(7,r.getStatus());return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void viewAll(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM rooms").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No rooms.");}catch(Exception e){}}
    public void searchById(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM rooms WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next())print(rs);else System.out.println("Not found.");}catch(Exception e){}}
    public void availableRooms(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM rooms WHERE status='Available'").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No available rooms.");}catch(Exception e){}}
    public boolean checkOut(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE rooms SET status='Available',guest_name='N/A' WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean delete(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("DELETE FROM rooms WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void count(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT COUNT(*) FROM rooms").executeQuery();if(rs.next())System.out.println("Total Rooms: "+rs.getInt(1));}catch(Exception e){}}
    public void occupancyReport(){try{ResultSet r1=db.getConnection().prepareStatement("SELECT COUNT(*) FROM rooms WHERE status='Booked'").executeQuery();ResultSet r2=db.getConnection().prepareStatement("SELECT COUNT(*) FROM rooms WHERE status='Available'").executeQuery();if(r1.next())System.out.println("Booked: "+r1.getInt(1));if(r2.next())System.out.println("Available: "+r2.getInt(1));}catch(Exception e){}}
    public void sortByPrice(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM rooms ORDER BY price_per_night DESC").executeQuery();while(rs.next())print(rs);}catch(Exception e){}}
}
